version: '3'

volumes:
    grafanavol:

services:
  collectd:
    image: fr3nd/collectd
    privileged: true
    network_mode: host
    volumes:
      - /proc:/mnt/proc:ro
      - ./collectd.conf:/etc/collectd/collectd.conf
  influxdb:
    image: influxdb:1.5.4
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
    volumes:
      - /var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db:ro
  grafana:
    image: grafana/grafana:6.2.4
    ports:
      - "3000:3000"
    volumes:
      - "./grafanavol:/var/lib/grafana"
    user: ${GRAFANA_USER_ID}

